// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package fb

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type ItemUnionWrapper struct {
	_tab flatbuffers.Table
}

func GetRootAsItemUnionWrapper(buf []byte, offset flatbuffers.UOffsetT) *ItemUnionWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &ItemUnionWrapper{}
	x.Init(buf, n+offset)
	return x
}

func FinishItemUnionWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsItemUnionWrapper(buf []byte, offset flatbuffers.UOffsetT) *ItemUnionWrapper {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &ItemUnionWrapper{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedItemUnionWrapperBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *ItemUnionWrapper) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *ItemUnionWrapper) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *ItemUnionWrapper) ItemType() ItemUnion {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return ItemUnion(rcv._tab.GetByte(o + rcv._tab.Pos))
	}
	return 0
}

func (rcv *ItemUnionWrapper) MutateItemType(n ItemUnion) bool {
	return rcv._tab.MutateByteSlot(4, byte(n))
}

func (rcv *ItemUnionWrapper) Item(obj *flatbuffers.Table) bool {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		rcv._tab.Union(obj, o)
		return true
	}
	return false
}

func ItemUnionWrapperStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func ItemUnionWrapperAddItemType(builder *flatbuffers.Builder, itemType ItemUnion) {
	builder.PrependByteSlot(0, byte(itemType), 0)
}
func ItemUnionWrapperAddItem(builder *flatbuffers.Builder, item flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(item), 0)
}
func ItemUnionWrapperEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
