// Code generated by the FlatBuffers compiler. DO NOT EDIT.

package entities

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type Archive struct {
	_tab flatbuffers.Table
}

func GetRootAsArchive(buf []byte, offset flatbuffers.UOffsetT) *Archive {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &Archive{}
	x.Init(buf, n+offset)
	return x
}

func FinishArchiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.Finish(offset)
}

func GetSizePrefixedRootAsArchive(buf []byte, offset flatbuffers.UOffsetT) *Archive {
	n := flatbuffers.GetUOffsetT(buf[offset+flatbuffers.SizeUint32:])
	x := &Archive{}
	x.Init(buf, n+offset+flatbuffers.SizeUint32)
	return x
}

func FinishSizePrefixedArchiveBuffer(builder *flatbuffers.Builder, offset flatbuffers.UOffsetT) {
	builder.FinishSizePrefixed(offset)
}

func (rcv *Archive) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *Archive) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *Archive) Id() int64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt64(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *Archive) MutateId(n int64) bool {
	return rcv._tab.MutateInt64Slot(4, n)
}

func (rcv *Archive) DateTrans() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *Archive) TransactionAmount() float64 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(8))
	if o != 0 {
		return rcv._tab.GetFloat64(o + rcv._tab.Pos)
	}
	return 0.0
}

func (rcv *Archive) MutateTransactionAmount(n float64) bool {
	return rcv._tab.MutateFloat64Slot(8, n)
}

func (rcv *Archive) Description() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(10))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func ArchiveStart(builder *flatbuffers.Builder) {
	builder.StartObject(4)
}
func ArchiveAddId(builder *flatbuffers.Builder, id int64) {
	builder.PrependInt64Slot(0, id, 0)
}
func ArchiveAddDateTrans(builder *flatbuffers.Builder, dateTrans flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dateTrans), 0)
}
func ArchiveAddTransactionAmount(builder *flatbuffers.Builder, transactionAmount float64) {
	builder.PrependFloat64Slot(2, transactionAmount, 0.0)
}
func ArchiveAddDescription(builder *flatbuffers.Builder, description flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(3, flatbuffers.UOffsetT(description), 0)
}
func ArchiveEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
